# Generated by Django 3.1.7 on 2021-03-23 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='БРЕНДЫ', max_length=255, unique=True, verbose_name='BRANDS')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(help_text='СТИЛЬ', max_length=255, verbose_name='STYLE')),
            ],
        ),
        migrations.CreateModel(
            name='MenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, null=True)),
                ('Size', models.CharField(max_length=10)),
                ('Price', models.PositiveIntegerField()),
                ('img', models.ImageField(null=True, upload_to='media/')),
                ('slug', models.SlugField(max_length=255)),
                ('type', models.CharField(choices=[('MAN', 'MAN'), ('WOMAN', 'WOMAN'), ('KIDS', 'KIDS')], max_length=255, null=True)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Brand', to='shop_uz.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Style', to='shop_uz.style')),
            ],
        ),
    ]
