# Generated by Django 3.1.7 on 2021-03-23 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_uz', '0003_auto_20210323_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicturesOfClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Image')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_uz.menmodel')),
            ],
            options={
                'verbose_name': 'Pictures of clothes',
            },
        ),
    ]
