# Generated by Django 3.1.7 on 2021-03-31 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_uz', '0004_picturesofclothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='url',
            field=models.SlugField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='picturesofclothes',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NAME', to='shop_uz.menmodel'),
        ),
    ]
