# Generated by Django 3.1.7 on 2021-03-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_uz', '0005_auto_20210331_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='img',
            field=models.ImageField(null=True, upload_to='meida/'),
        ),
    ]
