# Generated by Django 3.1.7 on 2021-04-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_uz', '0008_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='menmodel',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
